<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>Simulations</title><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'Courier New'; font-size:12pt; font-weight:400; font-style:normal;">
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;">[Shadow](http://shadow.github.io/)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;"><span style=" font-weight:600;">* Summary: </span>Shadow is a unique, open source <a href="http://wikipedia.org/wiki/Discrete_event_simulation"><span style=" text-decoration: underline; color:#0000ff;">discrete-event network simulator</span></a> that runs real applications like <a href="https://www.torproject.org/"><span style=" text-decoration: underline; color:#0000ff;">Tor</span></a>. Shadow combines the accuracy of <a href="http://wikipedia.org/wiki/Emulator"><span style=" text-decoration: underline; color:#0000ff;">emulation</span></a> with the efficiency and control of <a href="http://wikipedia.org/wiki/Computer_simulation"><span style=" text-decoration: underline; color:#0000ff;">simulation</span></a>, achieving the best of both approaches<span style=" font-weight:600;"> </span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;"><span style=" font-size:11pt;">[Hflow2](https://projects.honeynet.org/hflow)</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:36px;"><span style=" font-size:11pt;">* Data Analysis System</span></p></body></html>